name: Docker Image (tailscale)

on:
  schedule:
    - cron: '30 00 * * 5'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  DOCKERHUB_USERNAME: cyberwormuk

jobs:
  ghcr_publish:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log-in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log-in to registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER }}

      - name: Build and push tailscale
        uses: docker/build-push-action@v6
        id: push
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          file: ./Containerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/tailscale:latest
            ${{ env.DOCKERHUB_USERNAME }}/tailscale:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/tailscale
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Build and push tailscale-min
        uses: docker/build-push-action@v6
        id: pushmin
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          file: ./Containerfile.minimal
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.actor }}/tailscale-min:latest
            ${{ env.DOCKERHUB_USERNAME }}/tailscale-min:latest

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attestmin
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.actor }}/tailscale-min
          subject-digest: ${{ steps.pushmin.outputs.digest }}
          push-to-registry: true