name: remove old tailscale
on:
  workflow_dispatch:
  schedule:
    - cron: '00 23 * * 6'
jobs:
  remove-old-tailscale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'tailscale'
          package-type: 'container'
          min-versions-to-keep: 30
          delete-only-untagged-versions: 'true'
          token: ${{ secrets.PAT }}
